### ISSUE TITLE
View not in ParallaxScrollView gets parallax effect

### ISSUE THREAD

**Issue by szoszig** [nirhart/ParallaxScroll#26]
Hi
I have a problem. I implemented your parallaxsrollview, and it worked fine (big thx).
Later there was an idea to put a view over the srollview like a header, and it is changing its alpha as you scroll. To achive this, i had to change my scroll container linearlayout to relative. This way it worked, but the srcollview didn't contain all of the views it should. I searched for a solution, and i found, if i put the whole layout in a relativelayout, and in that the original parallaxscrollview with linearlayout, and later in the xml i added the framelayout.
It almost worked, but this framelayout got the parallax effect. It is a little bit strange for me.
Any idea?
thx

**Comment by DevikaSrinivasan** [comment]
zoom factor is available in this dependency?
