### ISSUE TITLE
Math to get the amount of parallaxedview's height hidden?

### ISSUE THREAD

**Issue by meetshawn** [nirhart/ParallaxScroll#43]
I want to resize some of the objects inside my parallaxed view to the viewable area.

Could you tell me how the offset is calculated?

**Comment by nirhart** [comment]
It's all open source, https://github.com/nirhart/ParallaxScroll/blob/master/ParallaxScroll/src/com/nirhart/parallaxscroll/views/ParallaxScrollView.java#L66
